/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "and_gate.v:1.1-5.10" *)
module andgate(y, a, b);
  (* src = "and_gate.v:3.7-3.8" *)
  input a;
  wire a;
  (* src = "and_gate.v:3.9-3.10" *)
  input b;
  wire b;
  (* src = "and_gate.v:2.8-2.9" *)
  output y;
  wire y;
  assign y = b & a;
endmodule
